### ISSUE TITLE
[Bug] Developer comment with `_comment` not updated/added with existing keys

### ISSUE THREAD

**Issue by rothlis** [transifex/transifex-javascript#116] opened 2022-02-07 15:06 UTC
**Current Behavior**
We are using `@transifex/react` with Transifex Native. When pushing a new string with a `_comment` option, it gets uploaded fine. However, if you update later the `_comment` field, pushing again won't update the developer comments on Transifex.

**Expected Behavior**
Changing the `_comment` field of an existing key should update the developer comment on next push.

**Steps to Reproduce**
1. `t('Foo')`
2. *push* `Created strings: 1`
3. t('Foo', { _comment: `I am a comment` })
4. *push* `Skipped strings: 1`

**Possible Solution**
Updating the `_charlimit` option does correctly update the string. So `_comment` should follow the behaviour of `_charlimit`?

**Comment by nbasili** [comment] 2022-02-08 09:19
This is not a bug on the SDK. There is a related to a [Transifex API endpoint](https://developers.transifex.com/reference/patch_resource-strings-resource-string-id) that allows you to modify a source string metadata. 

Unfortunately PATCHing the `comment` is not there yet. The Transifex API team will update the endpoint, and with that in place, this will be fixed on [Transifex Delivery Service - CDS](https://github.com/transifex/transifex-delivery). 

Let's keep this issue open though for further follow-ups.

**Comment by nbasili** [comment] 2022-02-24 07:46
The issue has been fixed on: https://github.com/transifex/transifex-delivery/pull/44

**Closed by nbasili** 2022-02-24 07:46 UTC
Labels: bug
